CREATE TABLE [Users] (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    FullName NVARCHAR(100),
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Country VARCHAR(100),
    Phone VARCHAR(15),
    Timestamp DATETIME DEFAULT GETDATE(),
    isAdmin BIT DEFAULT 0 NOT NULL
);

CREATE TABLE Admins (
    AdminID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT UNIQUE NOT NULL,
    Role NVARCHAR(50),
    LastLogin DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Pages (
    PageID INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(1000),
    CreatedAt DATETIME DEFAULT GETDATE(),
    CreatedBy INT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES [Users](UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PageMembers (
    PageMemberID INT PRIMARY KEY IDENTITY(1,1),
    PageID INT NOT NULL,
    UserID INT NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    FOREIGN KEY (PageID) REFERENCES Pages(PageID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE Posts (
    PostID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    PageID INT,
    Timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PageID) REFERENCES Pages(PageID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Comments (
    CommentID INT PRIMARY KEY IDENTITY(1,1),
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PostID) REFERENCES Posts(PostID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE Shares (
    ShareID INT PRIMARY KEY IDENTITY(1,1),
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    ShareDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PostID) REFERENCES Posts(PostID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Friendships (
    FriendshipID INT PRIMARY KEY IDENTITY(1,1),
    UserID1 INT NOT NULL,
    UserID2 INT NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (Status IN ('Pending', 'Accepted', 'Rejected')),
    FOREIGN KEY (UserID1) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (UserID2) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Likes (
    LikeID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    PostID INT NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (PostID) REFERENCES Posts(PostID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE Notifications (
    NotificationID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE Chats (
    ChatID INT PRIMARY KEY IDENTITY(1,1),
    User1ID INT NOT NULL,
    User2ID INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (User1ID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (User2ID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Messages (
    MessageID INT PRIMARY KEY IDENTITY(1,1),
    ChatID INT NOT NULL,
    SenderID INT NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ChatID) REFERENCES Chats(ChatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (SenderID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


--CREATE TABLE Reports (
--    ReportID INT PRIMARY KEY IDENTITY(1,1),
--    ReporterID INT NOT NULL,
--    ReportedPostID INT NULL,
--    ReportedCommentID INT NULL,
--    ReportReason NVARCHAR(255) NOT NULL,
--    Timestamp DATETIME DEFAULT GETDATE(),
--    FOREIGN KEY (ReporterID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
--    FOREIGN KEY (ReportedPostID) REFERENCES Posts(PostID) ON DELETE NO ACTION ON UPDATE NO ACTION,
--    FOREIGN KEY (ReportedCommentID) REFERENCES Comments(CommentID) ON DELETE NO ACTION ON UPDATE NO ACTION
--);

--CREATE TABLE Settings (
--    SettingID INT PRIMARY KEY IDENTITY(1,1),
--    UserID INT NOT NULL,
--    NotificationPreference BIT DEFAULT 1,  -- 1 for enabled, 0 for disabled
--    PrivacyLevel NVARCHAR(50) DEFAULT 'Public',
--    FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
--);
